#!/bin/sh
# Simple script for running a maven project from the terminal

env MAVEN_OPTS='-Xmx1024M -d64 -server -XX:+UseConcMarkSweepGC -Dcom.sun.management.jmxremote'

mvn clean -Dtest=com.geosnappr.backend.ImportRoutesTest test
